### PR TITLE
add `Connection.use_(certificate|privatekey)`

### PR DESCRIPTION
**Pull request by mhils**
(depends on cryptography 38)

Follow-up to https://github.com/pyca/cryptography/pull/7210.  :)
I've added comments to point out the duplication between Context and Connection. Let me know if you want those out, happy to adjust to whatever style you prefer.

### CODE REVIEW

**Comment by reaperhulk** [comment]
cryptography 38 is out now 😄

**Comment by reaperhulk** [comment]
Conflict here due to the new pinning, but we should get this reviewed ASAP 😄

**Review by reaperhulk — APPROVED** [review]

**Comment by balloob** [comment]
This PR has not updated the changelog. Changelog for 22.1 still mentions Cryptography 37 as the minimum version.

**Comment by reaperhulk** [comment]
@balloob Thanks for the report, we've got a changelog fix up in https://github.com/pyca/pyopenssl/pull/1150 although we may also need to spin some knobs on readthedocs as well since this won't fix the `stable` tag.

**Pull request merged**
