### PR TITLE
Do not litter working dir

### PR DESCRIPTION
**Pull request by hynek**
This PR cleans up the handling of temporary files such that the CWD is not filled with them.

It changes the approach to creating a directory which it kills afterwards instead of keeping track of single files.

Some adjacent lines have been also cleaned up.

No code except tests is touched by this PR.

### CODE REVIEW

**Comment by hynek** [comment]
One thing I would suggest is to add the snowman unconditionally to all tmp files to simplify the code some more.

**Comment by hynek** [comment]
I’ve simplified a bunch, r4r!

**Comment by reaperhulk** [comment]
LGTM. The way `SSL_CTX_load_verify_locations` works is terrible. I haven't dug deeply yet but I bet there's a way to do that without requiring files on disk.

**Comment by reaperhulk** [comment]
(But that is an issue for a future PR)

**Pull request merged**
