### PR TITLE
Fix test_set_tmp_ecdh on OpenSSL 1.0.2

### PR DESCRIPTION
**Pull request by hynek**
Only one failure left after this!

### CODE REVIEW

**Comment by lvh** [comment]
Hm; how will we know when/if this is fixed? It sounds from the comment that this is just a broken impl and it's actually supposed to work?

**Comment by hynek** [comment]
It’s a shitload of curves that come with OpenSSL.  it would be enough to test the three major ones too.

**Comment by hynek** [comment]
FTR

```
<Curve u'c2pnb176v1'>
<Curve u'wap-wsg-idm-ecid-wtls6'>
<Curve u'wap-wsg-idm-ecid-wtls3'>
<Curve u'secp256k1'>
<Curve u'wap-wsg-idm-ecid-wtls5'>
<Curve u'secp384r1'>
<Curve u'secp521r1'>
<Curve u'sect571k1'>
<Curve u'prime192v1'>
<Curve u'brainpoolP224t1'>
<Curve u'c2tnb431r1'>
<Curve u'prime192v2'>
<Curve u'sect239k1'>
<Curve u'prime192v3'>
<Curve u'brainpoolP224r1'>
<Curve u'brainpoolP512r1'>
<Curve u'prime239v1'>
<Curve u'c2tnb191v1'>
<Curve u'prime239v2'>
<Curve u'brainpoolP192t1'>
<Curve u'c2tnb359v1'>
<Curve u'prime239v3'>
<Curve u'sect571r1'>
<Curve u'prime256v1'>
<Curve u'brainpoolP512t1'>
<Curve u'brainpoolP192r1'>
<Curve u'brainpoolP384r1'>
<Curve u'sect113r1'>
<Curve u'sect283k1'>
<Curve u'sect113r2'>
<Curve u'brainpoolP160t1'>
<Curve u'c2pnb272w1'>
<Curve u'sect131r1'>
<Curve u'c2tnb191v2'>
<Curve u'sect131r2'>
<Curve u'brainpoolP160r1'>
<Curve u'wap-wsg-idm-ecid-wtls4'>
<Curve u'sect163k1'>
<Curve u'c2pnb163v1'>
<Curve u'sect163r1'>
<Curve u'Oakley-EC2N-4'>
<Curve u'brainpoolP256t1'>
<Curve u'sect163r2'>
<Curve u'brainpoolP256r1'>
<Curve u'sect283r1'>
<Curve u'sect193r1'>
<Curve u'Oakley-EC2N-3'>
<Curve u'wap-wsg-idm-ecid-wtls1'>
<Curve u'sect193r2'>
<Curve u'brainpoolP320t1'>
<Curve u'c2tnb191v3'>
<Curve u'c2tnb239v3'>
<Curve u'sect233k1'>
<Curve u'wap-wsg-idm-ecid-wtls12'>
<Curve u'sect233r1'>
<Curve u'c2pnb163v2'>
<Curve u'c2tnb239v2'>
<Curve u'secp112r1'>
<Curve u'wap-wsg-idm-ecid-wtls11'>
<Curve u'c2pnb368w1'>
<Curve u'secp112r2'>
<Curve u'sect409k1'>
<Curve u'secp128r1'>
<Curve u'wap-wsg-idm-ecid-wtls10'>
<Curve u'secp128r2'>
<Curve u'c2pnb208w1'>
<Curve u'secp160k1'>
<Curve u'wap-wsg-idm-ecid-wtls9'>
<Curve u'c2pnb304w1'>
<Curve u'secp160r1'>
<Curve u'c2pnb163v3'>
<Curve u'secp160r2'>
<Curve u'wap-wsg-idm-ecid-wtls8'>
<Curve u'secp192k1'>
<Curve u'brainpoolP320r1'>
<Curve u'sect409r1'>
<Curve u'secp224k1'>
<Curve u'wap-wsg-idm-ecid-wtls7'>
<Curve u'secp224r1'>
<Curve u'brainpoolP384t1'>
<Curve u'c2tnb239v1'>
```

**Comment by lvh** [comment]
Sorry, I'm not sure I understand: "It’s a shitload of curves that come with OpenSSL."; those curves you mentioned are the remaining ones that don't start with Oakley, right?

**Comment by hynek** [comment]
No, I’m just showing what curves come with OPenSSL and that it’s not really our problem that some of them don’t load properly. :)

**Comment by lvh** [comment]
Okay, cool. And it also breaks in the versions of OpenSSL we're testing with? (I'm trying to figure out why we don't need a test for this behavior, i.e. that loading curves doesn't produce a bunch of noise on the error queue -- that test should keep working even after we remove this code, once OpenSSL fixes their bug.)

**Comment by hynek** [comment]
This is the penultimate bug that makes it impossible to run pyOpenSSL tests on 1.0.2 (ie. OS X with wheel or homebrew).

**Comment by lvh** [comment]
Right;  I understand why this patch is important, but I don't understand why there isn't a unit test to check that it helps.

**Pull request merged**
