### PR TITLE
Switch to new notBefore/After APIs

### PR DESCRIPTION
**Pull request by neheb**
Related: https://github.com/pyca/cryptography/pull/4914

### CODE REVIEW

**Comment by neheb** [comment]
Rebased. This passes.

**Comment by reaperhulk** [comment]
What version of cryptography did we add these APIs? Do we need to update the minimum version?

**Comment by neheb** [comment]
Beats me. I was just looking through my open PRs and fixing them up.

**Comment by reaperhulk** [comment]
https://github.com/pyca/cryptography/commit/f5735cf25acd08222368a1db615bbf61d36b8007 Looks like 2.8 so we’ll need to update the minimum version to 2.8 for this.

**Comment by neheb** [comment]
I assume that means the defines can be eliminated?

**Pull request merged**
