### PR TITLE
Add a tox environment for building documentation

### LINKED ISSUE #131: Tox build environment for building documentation
Since documentation should always be buildable, tox should try to build it. This should be a separate env, like #127.

This also makes it easier to add e.g. spelling and link checkers later.

### PR DESCRIPTION
**Pull request by lvh**
This closes #131.

### CODE REVIEW

**Comment by reaperhulk** [comment]
Woud you mind rebasing this now lvh? :)

**Comment by hynek** [comment]
couple notes:

- the _static thing is not necessary, we’ve killed it off in #231.
- we don’t need to pin Sphinx to 1.2.x, do we?
- we have py34 now

**Comment by lvh** [comment]
@hynek What would you prefer to see instead re: Sphinx?

**Comment by hynek** [comment]
I wouldn’t pin it at all; pyca/cryptography doesn’t either.

**Comment by lvh** [comment]
I'll rebase this once the other two things come through. Should be easier to just start from scratch though

**Comment by hynek** [comment]
agreed

**Comment by lvh** [comment]
Note to self, do this one once #127 is merged, but do it by closing this one + copypasta

**Comment by hynek** [comment]
note to @lvh, #127 is merged ;)

**Pull request closed without merging**
