### PR TITLE
Test on OpenSSL 1.1.0 with travis. Fixes #524

### LINKED ISSUE #524: Add OpenSSL 1.1.0 to travis

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
LGTM, although tests will fail until we merge the fixes we need. I'm inclined to merge this so that we can quickly fix the 1.1.0 bugs though.

**Comment by alex** [comment]
Unless there's a large volume of them, I'm content to simply fix them on this branch. If they are aplenty I'll add this to the allowed_failures section

**Comment by alex** [comment]
Found an OpenSSL bug in the process of working on this https://github.com/openssl/openssl/issues/1537

**Comment by alex** [comment]
Ok, another bug: https://github.com/openssl/openssl/issues/1563

**Comment by hynek** [comment]
pyOpenSSL is actually being useful!

**Comment by alex** [comment]
There are a few skips, but tests are passing on 1.1.0! Next steps:

- Send PRs cherry-picking some of the easy stuff here over to master
- Get the tests passing on 1.0.1 again (oops)
- Figure out what to do about the skips

**Pull request merged**
