### PR TITLE
Refactor and fix X509 certificate serial_number functions

### PR DESCRIPTION
**Pull request by socketpair**
And also allow to pass raw bytes to X509.set_serial_number()

### CODE REVIEW

**Comment by socketpair** [comment]
Unfortunatelly I cannot run tests for python2 since `cryptography` can not be installed on my system...

**Comment by StyleEX** [comment]
+1

**Comment by hynek** [comment]
How would you feel about adding a helper function that you’d use together with `set_serial_number_hex`?  It’s easy to test and generally speaking dispatch on types is a rather bad idea.

**Comment by socketpair** [comment]
Not sure I understand your right. Please be verbose :(

**Comment by hynek** [comment]
Right, because I made a mistake. :)

Another attempt to get it right: 

Instead of adding a new method and changing the existing `set_serial_number`, I’m arguing for something like: `x509.set_serial_number(hexstr_to_int(b"fffe"))` which doesn’t change the existing class and much simplifies the testing of the added code.

It’s more explicit in its intent and doesn’t hide possible bugs.

**Comment by socketpair** [comment]
Thinking that serial number is monotonically incrementing value is a bad idea. Actually it is not used in secure environment since  https://en.wikipedia.org/wiki/Predictable_serial_number_attack . In real scenarios, serial number is a random binary string of arbitrary length (someone use 8 bytes, someone 64).

Example of such vulnerability:
http://blog.erratasec.com/2008/12/not-all-md5-certs-are-vulnerable.html

So, it is much better to create new function (accepting raw bytes), and consider function accepting plain integer obsolete. And more over, some users who use obsolete technologies to generate serial numbers should call `set_serial_number_hex(hexlify(42))`.

So, for the first time ( 1-2 years?) it will be nice to support deprecated function, but with this:
https://docs.python.org/2/library/warnings.html

And also, it may be suitable to add `.set_random_serial_number()`, but it is a question about which random we should use....so it is not good API.

**Comment by socketpair** [comment]
For example

https://reborn.ru
serial number is  26:41:8d:fd:83:aa:85:a5:af:86:8f:64:45:75:a8:d9


So, I think, it is reasonable to switch to new API with some time. So, I added new function, and consider to make old API to be obsolete.

**Comment by socketpair** [comment]
Re-worked branch completely. Will not change API, but remove VERY WRONG code about small serial numbers. BN_hex2bn NEVER return original value, even if it was small.

**Comment by socketpair** [comment]
I'm tired to find and fix previous bugs, especially when tests are FAILED. I cannot fix bugs since code coverage find things that I did not change (just change indentation because code refactoring).

This fuck me hard, sorry. If you can't merge that, just say NO, and I will decline that pul request.

**Pull request closed without merging**
