### PR TITLE
Add pypy3 to Travis

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by Lukasa** [comment]
LGTM.

**Comment by alex** [comment]
pypy3 is Python 3.2, which we don't support.

On Sun, Dec 27, 2015 at 4:25 AM, Cory Benfield <notifications@github.com>
wrote:

> LGTM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/pyopenssl/pull/402#issuecomment-167396499>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by Lukasa** [comment]
Oh, yeah, there's that. Whoops!

**Comment by hynek** [comment]
This kind of only makes sense if pypy3 is going to support Python 3.3 (or later) soonish since we’ve dropped Python 3.2.

@alex?

**Comment by alex** [comment]
It's being worked on, but there's no timeline for when a 3.3 will be out, not worth adding a build which isn't passing and which we can't do anything to fix, IMO.

**Pull request closed without merging**
