### PR TITLE
Updated installation docs

### PR DESCRIPTION
**Pull request by flowerhack**
Installation docs were a bit confusing; I think these might be more clear/helpful.

### CODE REVIEW

**Comment by alex** [comment]
lgtm; @hynek or @exarkun ?

**Comment by hynek** [comment]
We’re working on it live. :)

**Comment by alex** [comment]
Awesome, yay!

On Mon, Apr 13, 2015 at 5:51 PM, Hynek Schlawack <notifications@github.com>
wrote:

> We’re working on it live. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/pyopenssl/pull/213#issuecomment-92511226>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by hynek** [comment]
I’m afraid this need a rebase.

**Comment by hynek** [comment]
Thanks and sorry for the CI-induced delays!

**Pull request merged**
