### PR TITLE
Add Context.set_tlsext_use_srtp

### PR DESCRIPTION
**Pull request by jlaine**
This allows negotiating SRTP keying material, which is useful when using
DTLS-SRTP, as WebRTC does for example.

This depends on:
https://github.com/pyca/cryptography/pull/4099

### CODE REVIEW

**Comment by jlaine** [comment]
I'm not sure what the best form would be for the "profiles" argument. Two possibilities:

- A colon-delimited bytestring : this mimics the OpenSSL API exactly, and works the same as existing Context.set_cipher_list for example

- A list of bytestrings : this feels somewhat more pythonic, but deviates from the OpenSSL API

Suggestions?

**Comment by reaperhulk** [comment]
I dislike the OpenSSL APIs for this, but pyOpenSSL generally doesn't abstract much away and since we already have an API that exposes colon delimited behavior it probably makes sense for this one to look like that as well.

One day we'll have a nice TLS API. pyOpenSSL won't be it...

**Comment by jlaine** [comment]
OK thanks for the feedback I'll write the corresponding API docs.

Quick question : any reason why we don't use sphinx.autodoc's automethod? It seems a shame to have to duplicate the docstrings everywhere.

**Comment by hynek** [comment]
We do for new code. Nobody wanted to spend their time to move everything to docstrings yet.

**Comment by jlaine** [comment]
Duly noted, I've updated my pull request to use automethod

**Comment by jlaine** [comment]
This requires #742

**Comment by jlaine** [comment]
@reaperhulk anything you'd like me to change with this PR?

**Comment by reaperhulk** [comment]
@jlaine could you rebase this?

**Comment by reaperhulk** [comment]
Actually I can resolve, nevermind :)

**Pull request merged**
