### PR TITLE
Remove deprecated tsafe module.

### PR DESCRIPTION
**Pull request by benjaminp**

### CODE REVIEW

**Comment by alex** [comment]
Been deprecated for 3 years... lgtm! @reaperhulk @hynek ?

**Comment by AdamIdriis** [comment]
Maybe the pretentious fake "Alex's" should stop wasting my Time, and find better things to do.
________________________________

**Comment by reaperhulk** [comment]
I am in favor, although it appears flake8 is upset about checking `examples` when that no longer exists. Since this PR didn't remove that it's time to reset the clock on CI breakage...

**Comment by AdamIdriis** [comment]
I'm sorry but this is confusing, I've been dealing with mutliple Alex and seemingly it's been on going
Unless it's code language I need to learn lol🤭

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
