### PR TITLE
Add SSL.Context.set_keylog_callback

### PR DESCRIPTION
**Pull request by mhils**
This builds on the bindings added in https://github.com/pyca/cryptography/pull/5187. :)

The PR should be ready, but this depends on the next minor cryptography release.

### CODE REVIEW

**Comment by rugk** [comment]
https://github.com/pyca/cryptography/pull/5187 ha sbeen merged. What is blocking this?

**Comment by mhils** [comment]
There's no cryptography release that includes https://github.com/pyca/cryptography/pull/5187 yet. 

Tests are passing here because `Cryptography_HAS_KEYLOG` always returns false and the actual code is never tested (as indicated by the decrease in code coverage).

**Comment by mhils** [comment]
I've rebase the PR onto master, all tests are passing now with cryptography 3.0 - thanks! 🍰 

Codecov is complaining about one missed line, but that seems to be a false-positive to me.

**Comment by mhils** [comment]
Yes, we suffer from that too. Thanks for the super quick merge again! ❤️

**Pull request merged**
