### PR TITLE
import stubs from typeshed

### PR DESCRIPTION
**Pull request by graingert**
fixes https://github.com/pyca/pyopenssl/issues/1032

### CODE REVIEW

**Review by reaperhulk — COMMENTED** [review]
I would prefer that we just run the mypy tests in the flake tox job and not add all these new environments.

**Comment by graingert** [comment]
> I would prefer that we just run the mypy tests in the flake tox job and not add all these new environments.

You need to run mypy once for each Python version and platform

**Comment by reaperhulk** [comment]
Why? We don’t do this on cryptography. Are the types so fragile that I need to be concerned about them breaking on different versions 3.6+?

**Comment by graingert** [comment]
> Why? We don’t do this on cryptography. Are the types so fragile that I need to be concerned about them breaking on different versions 3.6+?

Yeah I already had type errors on CI that passed locally because I only ran on one interpreter

**Comment by penguinolog** [comment]
> Are the types so fragile that I need to be concerned about them breaking on different versions 3.6+?

On python 3.6 - yes. Later `from __future__ import annotations` solve most problems

**Comment by graingert** [comment]
There's two different problems,
The first is that the typing syntax is different on different versions of Python you use `__future__ annotations` to use the new syntax.

The second is that different Python versions have different types and functions you run mypy on each Python version to solve this

**Comment by lovetox** [comment]
This can should be obsolete once #1089 is merged

**Comment by mhils** [comment]
Superseded by #1089 with inlined annotations. If someone would be willing to port over the annotations for `SSL.py` that would be most wonderful. 😃

**Pull request closed without merging**
