### PR TITLE
fix race condition in tests

### PR DESCRIPTION
**Pull request by mhils**
Fix race condition in tests which surfaced here: https://travis-ci.org/pyca/pyopenssl/jobs/72581102#L222

### CODE REVIEW

**Comment by hynek** [comment]
Would you mind elaborating on your approach?  That may expedite the review. :)

**Comment by mhils** [comment]
Sure. In a nutshell, the previous code was
````python
now = datetime.utcnow() + timedelta(seconds=100)
cert.gmtime_adj_notBefore(100)
self.assertEqual(cert.get_notBefore(), b(now.strftime("%Y%m%d%H%M%SZ")))
```
This fails if there is the second changes between the first and the second statement, as in the travis job above. The workaround is to capture a timestamp before and after the call to `cert.gmtime_adj_notBefore(100)` and make sure that `cert.get_notBefore()` is within that range.
Does this clear things up? :smiley:

**Comment by hynek** [comment]
Makes sense thanks.

**Comment by hynek** [comment]
You also may be interested in #266. ;)

**Pull request merged**
