### PR TITLE
Introduce a gate/check GHA job

### PR DESCRIPTION
**Pull request by webknjaz**
This is a mirror of https://github.com/pyca/cryptography/pull/7643.

https://github.com/marketplace/actions/alls-green#why

### CODE REVIEW

**Comment by webknjaz** [comment]
@alex @reaperhulk it looks like this repo doesn't have any checks listed in the branch protection. Is that intentional or forgotten?

**Comment by webknjaz** [comment]
_(the failures are caused by the codecov coverage upload script getting an HTTP 504 response)_

**Comment by alex** [comment]
I guess we'd say intentional. pyOpenSSL's CI isn't nearly as polished as
cryptography's. We don't object to required checks, we just don't spend
much time improving CI

בתאריך שבת, 24 בספט׳ 2022, 18:06, מאת Sviatoslav Sydorenko ‏<
***@***.***>:

**Comment by mhils** [comment]
Missed this PR in https://github.com/pyca/pyopenssl/pull/1283, sorry about that and thanks! 🍰

**Pull request closed without merging**
