### PR TITLE
Make pyOpenSSL compatible with openssl 1.1.0 again

### PR DESCRIPTION
**Pull request by ShaneHarvey**
I think this should fix https://github.com/pyca/pyopenssl/issues/975

### CODE REVIEW

**Comment by alex** [comment]
Ooops, look like CI regressed. We'll need to merge https://github.com/pyca/pyopenssl/pull/977 to fix it, then rebase this.

**Comment by alex** [comment]
Attempting to do a thing to get CI to pass.

**Comment by reaperhulk** [comment]
Fix cherry-picked and merged with a CI change in #978. Thanks for the contribution!

**Comment by ShaneHarvey** [comment]
Thanks for the quick release!

**Pull request closed without merging**
