### PR TITLE
Add inline type annotations

### LINKED ISSUE #1032: merge types-pyopenssl into pyopenssl
It would be useful to merge the types-pyopenssl into pyopenssl.

It could start by just pasting the .pyi files into the repo and running check-stubs, but could also be iteratively improved to use inline type annotations and mypy type checking

See also https://github.com/twisted/twisted/pull/1484#issuecomment-890476456

### PR DESCRIPTION
**Pull request by lovetox**
- Prepare Package and CI
- Everything is typed except SSL.py
- Extensive use of Any type
- mypy yields no errors with this PR on strict mode
- On one method `# type: ignore` had to be used
- The only logic change which had to be done is factored out into its own commit

I would like to request a review for this PR, its a good starting point on the way to having the whole codebase type checked.

The package is not yet marked as `typed` because SSL.py is missing annotations which contains public API.

Fixes #1032

### CODE REVIEW

**Comment by lovetox** [comment]
Ok seems i have no clue about tox, maybe someone can help out with getting mypy running in the CI

**Comment by lovetox** [comment]
Ci runs now mypy but fails because of dependency on #1083

**Comment by lovetox** [comment]
Hi,

CI runs without error now, MR is ready for Review.

**Review by mhils — COMMENTED** [review]
Thanks for the PR! 😃 

Could you move mypy into a separate toxenv (similar to flake8)? AFAIK there's no benefit in running mypy on different Python versions (please correct me if I'm wrong). By moving it into a separate job we take it off the critical path.

The type hints so far look good to me. 👍

**Comment by lovetox** [comment]
It seems im unable to add another env, i tried (see commits in tox.ini) but it does not add the env to CI, im new to tox though maybe i did something wrong

**Comment by mhils** [comment]
You need to add a job in the workflow yaml in `/.github`. :)

**Comment by lovetox** [comment]
Ok works now.

i opted to run mypy on the lowest supported version. This has the benefit of failing if anyone uses syntax or typing imports not supported by python 3.6. But one could argue this would be catched by other tests because this project has a high test coverage.

Tell me if you want to run it on latest version.

**Comment by mhils** [comment]
Sounds sensible to me. Once the minimum Python version is >=3.7, it
probably makes a lot of sense to opt into `from __future__ import
annotations` and just use the latest version. :)

**Review by mhils — COMMENTED** [review]
CI is currently not running what you think it is, see https://github.com/pyca/pyopenssl/runs/6436553928?check_suite_focus=true#step:5:53. I think that's because of the mismatch between `py-36-mypy` (tox.ini), `mypy` (tox.ini), and `py36-mypy` (ci.yml).

**Comment by lovetox** [comment]
Should be ok now

**Review by mhils — APPROVED** [review]
Looks good to me now, thanks a bunch! 😃 We still need SSL.py to be annotated to reap the benefits of this, but thank you for getting this started! 🍰

**Pull request merged**
