### PR TITLE
Fixed #322 -- removed code that already exists in cryptography

### LINKED ISSUE #322: Delete locking callback code, just use cryptography's

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by hynek** [comment]
Do we have any thread safety tests that can make us slightly confident this isn’t gonna break stuff?

**Comment by alex** [comment]
@hynek There's a couple of files in `leakcheck/` which you can run manually that use threads.

**Comment by hynek** [comment]
This is a bit too hairy for me. Can @reaperhulk have a look maybe?

**Comment by reaperhulk** [comment]
Two comments:

* I think hoisting the `init_static_locks` call up into _util.py right after the binding is initialized would be a more logical place for it to live.
* the cryptography implementation does not set `CRYPTO_set_id_callback`, so we may need to investigate what that really means. https://www.openssl.org/docs/manmaster/crypto/threads.html mentions that `CRYPTO_THREADID` deprecated `CRYPTO_set_id_callback` in 1.0.0+, but it's not clear to me what the consequence of not setting this callback is.

@public, you originally wrote the locking callback for cryptography, do you know if/why `CRYPTO_set_id_callback` (or the `CRYPTO_THREADID_set_callback`) are needed?

**Comment by alex** [comment]
@reaperhulk as far as I can tell from the openssl docs, `set_id_callback` and friends are totally deprecated, I don't think they do anything.

**Comment by reaperhulk** [comment]
`CRYPTO_THREADID_set_callback` is deprecated? It is the successor to `CRYPTO_set_id_callback` right?

**Comment by alex** [comment]
@reaperhulk sorry, it's not deprecated, but there's a default behavior which is perfectly fine, we're not adding any value by setting this callback.

**Comment by reaperhulk** [comment]
Ah, perfect. Then I'm :+1: on this once tests pass and will merge.

**Pull request merged**
