### PR TITLE
Make pyOpenSSL future-proof

### PR DESCRIPTION
**Pull request by hynek**
Notably stop breaking cryptography 1.3.

Based on #406.

### CODE REVIEW

**Comment by Lukasa** [comment]
LGTM, but I want someone from cryptography to take a look.

**Comment by alex** [comment]
Code looks fine, I'd rather something more precise than legacy though, how about "1.1" :-)

**Comment by hynek** [comment]
you mean as part of the tox env name?

**Comment by alex** [comment]
Yeah

On Sun, Jan 31, 2016 at 9:26 AM, Hynek Schlawack <notifications@github.com>
wrote:

> you mean as part of the tox env name?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/pyopenssl/pull/418#issuecomment-177511971>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by hynek** [comment]
done

**Pull request merged**
