### PR TITLE
Dedup meta data, use README as long_description

### LINKED ISSUE #247: Dedup meta information
Before a new release is made, the duplication of meta data throughout the project has to be fixed.

### PR DESCRIPTION
**Pull request by hynek**
I’ve moved all the relevant meta data into OpenSSL/version.py (and __init__.py; basically cryptography-style) and extract it from there in setup.py and the Sphinx conf.py.

Fixes #247 

Opinions?

### CODE REVIEW

**Comment by reaperhulk** [comment]
This mostly LGTM. Any reason you chose to use regexes rather than the `exec()` approach cryptography uses?

**Comment by hynek** [comment]
Hm it all started from the code you find in `doc/conf.py` and I’ve expanded it for all kinds of meta information.  Do you find the exec way superior?

**Comment by reaperhulk** [comment]
I don't have a preference on exec, just curious. This needs a rebase now.

**Comment by hynek** [comment]
Rebased and Travis is through.

**Pull request merged**
