### PR TITLE
Add dump_pkcs7_data function to crypto module.

### PR DESCRIPTION
**Pull request by ecdavis**
Right now there's a function to load PKCS#7 data from a buffer, but no function to dump PKCS#7 data to a buffer. This PR adds one.

### CODE REVIEW

**Comment by reaperhulk** [comment]
@ecdavis we've done a terrible job here leaving this unreviewed. Would you be able to rebase this so we can get it reviewed/merged ASAP? Sorry about that.

**Comment by hynek** [comment]
JFTR from cursory look:

- needs a changelog entry
- API docs use autodoc now

Thanks and sorry.

**Comment by jobec** [comment]
@reaperhulk  @hynek 

Any update on this?

We were missing the same feature and after implementing it ourselves we bumped into this MR. Is there anything I can help with to move this forward?

**Comment by reaperhulk** [comment]
@jobec if you want to rebase this in a new PR and add a changelog entry in the format we expect I can review it.

**Comment by reaperhulk** [comment]
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization.html#pkcs7 can parse pkcs7 as well as create signed pkcs7 payloads so I'm going to close this since better APIs are available outside of pyOpenSSL

**Pull request closed without merging**
