### PR TITLE
Convert the elliptic curve tests to be pytest-style

### PR DESCRIPTION
**Pull request by alexwlchan**
This is part of breaking up #561.

### CODE REVIEW

**Comment by alexwlchan** [comment]
So looking at Codecov, it looks like the bug is that we call `get_elliptic_curves()` and always get something back. In particular, the `test_some_curves()` test never executes the code path where we don't get some curves from OpenSSL.

This is [the same on master](https://codecov.io/gh/pyca/pyopenssl/src/e15e60a587efcddd61e391a8e5917291c98d554e/tests/test_crypto.py#L3889).

Has the supported OpenSSL version advanced to the point where every version has elliptic curve support?

**Comment by hynek** [comment]
A clear case of #485.

We don’t support 0.9.8 anymore but there’s no docs on when the EC crap has been added.

1.0.0!?  1.0.1?

Sadly, cryptography supports “OpenSSL 1.0.0-fips” but we don’t test against it so we don’t know if it even works.  Technically we should add Travis builders for all supported OpenSSLs. :'(

@reaperhulk do you know more?

**Comment by reaperhulk** [comment]
EC support is present even in 0.9.8. Depends what feature you specifically care about. Also, we drop 1.0.0 in cryptography 1.7, which is coming out next week. Probably Monday.

**Comment by hynek** [comment]
OK, @alexwlchan feel free to kill off no-EC-present code.  Next pyOpenSSL will be 1.0.1+ only.

**Comment by alexwlchan** [comment]
> feel free to kill off no-EC-present code

Done.

**Comment by hynek** [comment]
seems like we got rid of an import dep (flake8)

**Comment by hynek** [comment]
Thanks once again!

**Pull request merged**
