### PR TITLE
Improved examples

### PR DESCRIPTION
**Pull request by HYSUH**
Improved the code that creates the server,client and CA certificates by adding comments and variables.

Note:This is my first pull request using github. So I apologize if I have done anything incorrectly.

### CODE REVIEW

**Comment by hynek** [comment]
Hi, sorry for not coming back at your earlier.  You’re on to something with some of the changes but some are covered by #245.  Once  #245 is merged, I’ll gladly revisit more possible enhancements with you on this PR.

**Comment by hynek** [comment]
Since #245 is merged now, feel free to work on improving the examples some more!  They sure need it. :)

**Comment by hynek** [comment]
since this is not moving and not mergeable, I’m going to close it.  please absolutely feel free to open a new and revised PR!  thanks!

**Comment by HYSUH** [comment]
Sorry for not replying earlier. I will rework on a new PR. Thanks a lot!

**Pull request closed without merging**
