### PR TITLE
submit coverage whether or not travis actually succeeds.

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Comment by alex** [comment]
Is this better than `after_script`? (No opinions, just asking)

**Comment by reaperhulk** [comment]
I have no opinion either.

**Comment by alex** [comment]
I lied, I very very slightly think "after_script" is more appropriate

**Comment by reaperhulk** [comment]
Well since we're still waiting on CI let's just change it now :)

**Comment by alex** [comment]
A+

**Pull request merged**
